version: '3.8'

services:
  web:
    build: .
    container_name: python_app
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
